// packages/web-c-runtime/src/types.ts

export type ZeusPropType =
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'array'
  | 'function'
  | 'unknown'

export interface ZeusPropMeta {
  name: string
  attrName?: string
  type: ZeusPropType
  reflect?: boolean
  required?: boolean
  default?: unknown
}

export interface ZeusEventMeta {
  name: string
}

export interface ZeusSlotMeta {
  name: string
}

export interface ZeusLazyComponentMeta {
  tagName: string

  /**
   * Real component implementation chunk.
   * This function must be explicitly generated by the component library manifest,
   * so the runtime does not need to construct dynamic paths.
   */
  load: () => Promise<ZeusComponentModule | { default: ZeusComponentModule }>

  props: ZeusPropMeta[]
  events?: ZeusEventMeta[]
  slots?: ZeusSlotMeta[]

  /**
   * Default to true.
   */
  shadow?: boolean
}

export interface HostRef {
  host: HTMLElement
  meta: ZeusLazyComponentMeta

  connected: boolean
  loaded: boolean
  loading?: Promise<void>

  instance?: ZeusComponentInstance

  values: Map<string, unknown>

  queuedAttrs: Array<{
    name: string
    oldValue: string | null
    newValue: string | null
  }>

  reflectingAttrs: Set<string>
}

export interface ZeusComponentInstance {
  connected?(): void
  disconnected?(): void

  attributeChanged?(
    name: string,
    oldValue: string | null,
    newValue: string | null,
  ): void

  propertyChanged?(name: string, oldValue: unknown, newValue: unknown): void

  /**
   * Can return Node / Node[] / string.
   * If the component completes rendering itself, it can also return void.
   */
  render?(): void | string | Node | Node[]

  dispose?(): void
}

export interface ZeusComponentModule {
  createComponent(hostRef: HostRef): ZeusComponentInstance
}

export interface BootstrapLazyOptions {
  registry?: CustomElementRegistry
}
