// packages/web-c-runtime/src/types.ts

export type ZeusPropType =
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'array'
  | 'function'
  | 'unknown'

export interface ZeusPropMeta {
  name: string
  attrName?: string | false
  type: ZeusPropType
  reflect?: boolean
  default?: unknown
}

export interface ZeusLazyComponentMeta {
  tagName: string

  /**
   * Real component implementation chunk.
   * This function must be explicitly generated by the component library manifest,
   * so the runtime does not need to construct dynamic paths.
   */
  load: () => Promise<ZeusComponentModule | { default: ZeusComponentModule }>

  props: ZeusPropMeta[]

  /**
   * Default to true.
   */
  shadow?: boolean
}

export interface HostRef {
  host: HTMLElement
  meta: ZeusLazyComponentMeta

  connected: boolean
  loaded: boolean
  loading?: Promise<void>

  instance?: ZeusComponentInstance

  values: Map<string, unknown>

  reflectingAttrs: Set<string>

  readyWaiters: Array<{
    resolve(host: HTMLElement): void
    reject(error: unknown): void
  }>
}

export interface ZeusComponentInstance {
  connected?(): void
  disconnected?(): void

  propertyChanged?(name: string, oldValue: unknown, newValue: unknown): void

  /**
   * Can return Node / Node[] / string.
   * If the component completes rendering itself, it can also return void.
   */
  render?(): void | string | Node | Node[]

  dispose?(): void
}

export interface ZeusComponentModule {
  createComponent(hostRef: HostRef): ZeusComponentInstance
}

export interface BootstrapLazyOptions {
  registry?: CustomElementRegistry
}
