# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = ["*.snap", "*.json"]

[default.extend-words]
splitted = "splitted"
styl = "styl"

[default.extend-identifiers]
IIFEs = "IIFEs"
