packages:
  - 'packages/core/*'
  - 'packages/devtools/*'
  - 'packages/web-c/*'
  - 'packages/create/*'
  - 'examples/*'
  - 'benchmarks/*'
  - 'docs'

catalog:
  '@babel/parser': ^8.0.0
  '@babel/types': ^8.0.0
  '@napi-rs/cli': 3.6.2
  '@napi-rs/wasm-runtime': ^1.1.1
  vite: ^8.0.5

shellEmulator: true
