packages:
  - packages/*
  - playground/*

allowBuilds:
  esbuild: true
  puppeteer: false
  simple-git-hooks: true
  unrs-resolver: true

catalog:
  '@babel/core': ^7.29.0
  '@babel/parser': ^7.29.0
  '@babel/plugin-syntax-jsx': ^7.28.6
  '@babel/preset-env': ^7.29.0
  '@babel/preset-typescript': ^7.28.5
  '@babel/types': ^7.29.0
  '@napi-rs/cli': ^3.5.1
  '@napi-rs/wasm-runtime': ^1.1.1
  '@types/babel__core': 7.20.5
  vite: ^8.0.5

minimumReleaseAgeExclude:
  - '@typescript/native-preview-darwin-arm64@7.0.0-dev.20260524.1'
  - '@typescript/native-preview-darwin-x64@7.0.0-dev.20260524.1'
  - '@typescript/native-preview-linux-arm64@7.0.0-dev.20260524.1'
  - '@typescript/native-preview-linux-arm@7.0.0-dev.20260524.1'
  - '@typescript/native-preview-linux-x64@7.0.0-dev.20260524.1'
  - '@typescript/native-preview-win32-arm64@7.0.0-dev.20260524.1'
  - '@typescript/native-preview-win32-x64@7.0.0-dev.20260524.1'
  - '@typescript/native-preview@7.0.0-dev.20260524.1'
  - '@vitest/eslint-plugin@1.6.18'

shellEmulator: true
