packages:
  - packages/*
  - playground/*
  - tools/*
  - examples/*
  - compiler/*

catalog:
  '@babel/core': ^7.24.7
  '@babel/parser': ^7.24.7
  '@babel/preset-env': ^7.24.7
  '@babel/preset-typescript': ^7.24.7
  '@babel/types': ^7.24.7
  '@napi-rs/cli': ^3.5.1
  '@napi-rs/wasm-runtime': ^1.0.0
  '@types/babel__core': 7.20.5
  vite: ^8.0.0-beta.7

shellEmulator: true
verifyDepsBeforeRun: install
