const PORTABLE_GLOBAL_TYPE_REFERENCES = new Set([
  'AbortSignal',
  'AddEventListenerOptions',
  'Array',
  'Blob',
  'CustomEvent',
  'Date',
  'Element',
  'Event',
  'EventListenerOptions',
  'File',
  'FocusEvent',
  'FormData',
  'Function',
  'HTMLElement',
  'InputEvent',
  'KeyboardEvent',
  'Map',
  'MouseEvent',
  'Node',
  'Omit',
  'Partial',
  'Pick',
  'PointerEvent',
  'Promise',
  'PromiseLike',
  'Readonly',
  'ReadonlyArray',
  'ReadonlyMap',
  'ReadonlySet',
  'Record',
  'Required',
  'Set',
  'URL',
  'UIEvent',
])

export function isPortableTypeReference(name: string): boolean {
  return PORTABLE_GLOBAL_TYPE_REFERENCES.has(name)
}
