export const VOID_ELEMENTS: readonly string[] = [
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
  'colgroup',
  'math',
  'mi',
  'mo',
  'mn',
  'ms',
  'mtext',
  'mspace',
  'mglyph',
  'malert',
  'path',
  'circle',
  'ellipse',
  'line',
  'polygon',
  'polyline',
  'rect',
  'stop',
  'use',
  'image',
  'symbol',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
]

export const SVG_ELEMENTS: ReadonlySet<string> = new Set([
  'svg',
  'a',
  'altGlyph',
  'altGlyphDef',
  'altGlyphItem',
  'animate',
  'animateColor',
  'animateMotion',
  'animateTransform',
  'circle',
  'clipPath',
  'color-profile',
  'cursor',
  'defs',
  'desc',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
  'filter',
  'font',
  'font-face',
  'font-face-format',
  'font-face-name',
  'font-face-src',
  'font-face-uri',
  'foreignObject',
  'g',
  'glyph',
  'glyphRef',
  'hkern',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'metadata',
  'missing-glyph',
  'mpath',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'set',
  'stop',
  'style',
  'switch',
  'symbol',
  'text',
  'textPath',
  'title',
  'tref',
  'tspan',
  'use',
  'view',
  'vkern',
])

export const DELEGATED_EVENTS: ReadonlySet<string> = new Set([
  'click',
  'mousedown',
  'mouseup',
  'mousemove',
  'mouseenter',
  'mouseleave',
  'mouseover',
  'mouseout',
  'contextmenu',
  'dblclick',
  'touchstart',
  'touchend',
  'touchmove',
  'touchcancel',
  'keydown',
  'keyup',
  'keypress',
  'input',
  'change',
  'submit',
  'reset',
  'focus',
  'blur',
  'load',
  'error',
  'abort',
  'scroll',
  'drag',
  'dragend',
  'dragenter',
  'dragexit',
  'dragleave',
  'dragover',
  'dragstart',
  'drop',
  'paste',
  'copy',
  'cut',
  'compositionend',
  'compositionstart',
  'compositionupdate',
])

export const DOM_PROPERTIES: Record<string, string> = {
  className: 'class',
  htmlFor: 'for',
  tabIndex: 'tabindex',
  readOnly: 'readOnly',
  maxLength: 'maxLength',
  autoComplete: 'autoComplete',
  autoCapitalize: 'autoCapitalize',
  autoFocus: 'autoFocus',
  noValidate: 'noValidate',
  formAction: 'formAction',
  formEncType: 'formEncType',
  formMethod: 'formMethod',
  formNoValidate: 'formNoValidate',
  formTarget: 'formTarget',
  crossOrigin: 'crossOrigin',
  accessKey: 'accessKey',
  autoPlay: 'autoPlay',
  encType: 'encType',
  noShade: 'noShade',
  playInline: 'playInline',
  rows: 'rows',
  cols: 'cols',
  rowSpan: 'rowSpan',
  colSpan: 'colSpan',
  frameBorder: 'frameBorder',
  useMap: 'useMap',
  wrap: 'wrap',
  contentEditable: 'contentEditable',
  spellCheck: 'spellCheck',
  translate: 'translate',
  viewBox: 'viewBox',
  xLink: 'xlink',
  xmlBase: 'xml:base',
  xmlLang: 'xml:lang',
  xmlSpace: 'xml:space',
}

export const CHILD_PROPERTIES: ReadonlySet<string> = new Set([
  'innerHTML',
  'textContent',
  'innerText',
  'value',
  'checked',
])

export const BOOLEAN_ATTRIBUTES: ReadonlySet<string> = new Set([
  'async',
  'autofocus',
  'autoplay',
  'checked',
  'controls',
  'default',
  'defer',
  'disabled',
  'formNoValidate',
  'hidden',
  'indeterminate',
  'ismap',
  'loop',
  'multiple',
  'muted',
  'nomodule',
  'novalidate',
  'open',
  'playsinline',
  'readonly',
  'required',
  'reversed',
  'seamless',
  'selected',
  'truespeed',
])

export const SVG_NAMESPACES: Record<string, string> = {
  xlink: 'http://www.w3.org/1999/xlink',
  xml: 'http://www.w3.org/XML/1998/namespace',
  xmlns: 'http://www.w3.org/2000/xmlns/',
  svg: 'http://www.w3.org/2000/svg',
}

export const RESERVED_NAMESPACES: ReadonlySet<string> = new Set([
  'class',
  'on',
  'oncapture',
  'style',
  'use',
  'prop',
  'attr',
  'bool',
])
