/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DemoButtonVariant } from "./components/z-demo-button/z-demo-button";
import { Event } from "@stencil/core";
export { DemoButtonVariant } from "./components/z-demo-button/z-demo-button";
export { Event } from "@stencil/core";
export namespace Components {
    interface ZDemoButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'default'
         */
        "variant": DemoButtonVariant;
    }
    interface ZDemoInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface ZDemoButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZDemoButtonElement;
}
export interface ZDemoInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZDemoInputElement;
}
declare global {
    interface HTMLZDemoButtonElementEventMap {
        "press": { nativeEvent: MouseEvent };
    }
    interface HTMLZDemoButtonElement extends Components.ZDemoButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLZDemoButtonElementEventMap>(type: K, listener: (this: HTMLZDemoButtonElement, ev: ZDemoButtonCustomEvent<HTMLZDemoButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLZDemoButtonElementEventMap>(type: K, listener: (this: HTMLZDemoButtonElement, ev: ZDemoButtonCustomEvent<HTMLZDemoButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLZDemoButtonElement: {
        prototype: HTMLZDemoButtonElement;
        new (): HTMLZDemoButtonElement;
    };
    interface HTMLZDemoInputElementEventMap {
        "value-change": { value: string; nativeEvent: Event };
        "focus-change": { focused: boolean; nativeEvent: FocusEvent };
    }
    interface HTMLZDemoInputElement extends Components.ZDemoInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLZDemoInputElementEventMap>(type: K, listener: (this: HTMLZDemoInputElement, ev: ZDemoInputCustomEvent<HTMLZDemoInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLZDemoInputElementEventMap>(type: K, listener: (this: HTMLZDemoInputElement, ev: ZDemoInputCustomEvent<HTMLZDemoInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLZDemoInputElement: {
        prototype: HTMLZDemoInputElement;
        new (): HTMLZDemoInputElement;
    };
    interface HTMLElementTagNameMap {
        "z-demo-button": HTMLZDemoButtonElement;
        "z-demo-input": HTMLZDemoInputElement;
    }
}
declare namespace LocalJSX {
    interface ZDemoButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onPress"?: (event: ZDemoButtonCustomEvent<{ nativeEvent: MouseEvent }>) => void;
        /**
          * @default 'default'
         */
        "variant"?: DemoButtonVariant;
    }
    interface ZDemoInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "onFocus-change"?: (event: ZDemoInputCustomEvent<{ focused: boolean; nativeEvent: FocusEvent }>) => void;
        "onValue-change"?: (event: ZDemoInputCustomEvent<{ value: string; nativeEvent: Event }>) => void;
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface ZDemoButtonAttributes {
        "disabled": boolean;
        "variant": DemoButtonVariant;
    }
    interface ZDemoInputAttributes {
        "disabled": boolean;
        "invalid": boolean;
        "placeholder": string;
        "value": string;
    }

    interface IntrinsicElements {
        "z-demo-button": Omit<ZDemoButton, keyof ZDemoButtonAttributes> & { [K in keyof ZDemoButton & keyof ZDemoButtonAttributes]?: ZDemoButton[K] } & { [K in keyof ZDemoButton & keyof ZDemoButtonAttributes as `attr:${K}`]?: ZDemoButtonAttributes[K] } & { [K in keyof ZDemoButton & keyof ZDemoButtonAttributes as `prop:${K}`]?: ZDemoButton[K] };
        "z-demo-input": Omit<ZDemoInput, keyof ZDemoInputAttributes> & { [K in keyof ZDemoInput & keyof ZDemoInputAttributes]?: ZDemoInput[K] } & { [K in keyof ZDemoInput & keyof ZDemoInputAttributes as `attr:${K}`]?: ZDemoInputAttributes[K] } & { [K in keyof ZDemoInput & keyof ZDemoInputAttributes as `prop:${K}`]?: ZDemoInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "z-demo-button": LocalJSX.IntrinsicElements["z-demo-button"] & JSXBase.HTMLAttributes<HTMLZDemoButtonElement>;
            "z-demo-input": LocalJSX.IntrinsicElements["z-demo-input"] & JSXBase.HTMLAttributes<HTMLZDemoInputElement>;
        }
    }
}
