// packages/web-c/component-dts/src/generateLoaderDts.ts

import type { ComponentManifest } from '@zeus-js/component-analyzer'

export function generateLoaderDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateLoaderComponentDts(component))
    lines.push('')
  }

  lines.push('export interface DefineCustomElementsOptions {')
  lines.push('  registry?: CustomElementRegistry;')
  lines.push('}')
  lines.push('')
  lines.push('export declare function defineCustomElements(')
  lines.push('  options?: DefineCustomElementsOptions,')
  lines.push('): void;')
  lines.push('')
  lines.push(
    'export declare const defineLazyElements: typeof defineCustomElements;',
  )
  lines.push('')

  return lines.join('\n')
}

function generateLoaderComponentDts(
  component: ComponentManifest['components'][0],
): string {
  const elementTypeName = `${component.name}Element`
  const propsTypeName = `${component.name}Props`

  const lines: string[] = []

  // Props interface
  lines.push(`export interface ${propsTypeName} {`)
  for (const [name, prop] of Object.entries(component.props)) {
    const optional = !prop.required ? '?' : ''
    const type = formatPropType(prop.type)
    lines.push(`  ${name}${optional}: ${type}`)
  }
  lines.push('}')
  lines.push('')

  // Element interface
  lines.push(`export interface ${elementTypeName} extends HTMLElement {`)
  for (const [name, prop] of Object.entries(component.props)) {
    const optional = !prop.required ? '?' : ''
    const type = formatPropType(prop.type)
    lines.push(`  ${name}${optional}: ${type}`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function formatPropType(type: string): string {
  switch (type) {
    case 'string':
      return 'string'
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array':
      return 'unknown[]'
    case 'object':
      return 'Record<string, unknown>'
    case 'function':
      return '(...args: unknown[]) => unknown'
    default:
      return 'unknown'
  }
}
