import {
  formatEventType,
  formatPropType,
  isRequiredProp,
  safePropertyName,
} from './formatType'
import { getElementTypeName, getEventMapTypeName } from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export function generateComponentWCDts(component: ComponentRecord): string {
  const elementTypeName = getElementTypeName(component)
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  lines.push(generateEventMap(component))
  lines.push('')
  lines.push(generateElementInterface(component))
  lines.push('')
  lines.push(`export declare const ${component.exportName}: {`)
  lines.push(`  new (): ${elementTypeName}`)
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export function generateWCIndexDts(
  manifest: ComponentManifest,
  options: {
    getComponentImportPath: (component: ComponentRecord) => string
  },
): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')

  for (const component of manifest.components) {
    lines.push(
      `import type { ${getElementTypeName(component)} } from ${JSON.stringify(options.getComponentImportPath(component))}`,
    )
  }

  for (const component of manifest.components) {
    lines.push(
      `export * from ${JSON.stringify(options.getComponentImportPath(component))}`,
    )
  }

  lines.push('')
  lines.push('declare global {')
  lines.push('  interface HTMLElementTagNameMap {')

  for (const component of manifest.components) {
    lines.push(
      `    ${JSON.stringify(component.tag)}: ${getElementTypeName(component)}`,
    )
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

function generateEventMap(component: ComponentRecord): string {
  const eventMapName = getEventMapTypeName(component)
  const entries = Object.entries(component.events)
  const lines: string[] = []

  lines.push(`export interface ${eventMapName} {`)

  if (!entries.length) {
    lines.push('  [key: string]: CustomEvent<unknown>')
  } else {
    for (const [name, event] of entries) {
      lines.push(`  ${safePropertyName(name)}: ${formatEventType(event)}`)
    }
  }

  lines.push('}')
  return lines.join('\n')
}

function generateElementInterface(component: ComponentRecord): string {
  const elementTypeName = getElementTypeName(component)
  const eventMapName = getEventMapTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${elementTypeName} extends HTMLElement {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('')
  lines.push(`  addEventListener<K extends keyof ${eventMapName}>(`)
  lines.push('    type: K,')
  lines.push(
    `    listener: (this: ${elementTypeName}, ev: ${eventMapName}[K]) => unknown,`,
  )
  lines.push('    options?: boolean | AddEventListenerOptions,')
  lines.push('  ): void')
  lines.push('')
  lines.push(`  removeEventListener<K extends keyof ${eventMapName}>(`)
  lines.push('    type: K,')
  lines.push(
    `    listener: (this: ${elementTypeName}, ev: ${eventMapName}[K]) => unknown,`,
  )
  lines.push('    options?: boolean | EventListenerOptions,')
  lines.push('  ): void')
  lines.push('}')

  return lines.join('\n')
}
