import { formatEventType, safePropertyName } from './formatType'
import { generateElementType } from './generateElementType'
import { generatePropTypeDeclarations } from './generatePropTypeDeclarations'
import {
  getElementTypeName,
  getEventMapTypeName,
  getGeneratedDeclarationNames,
} from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

interface GenerateComponentWCDtsOptions {
  exportPropTypes?: boolean
  reservedNames?: ReadonlySet<string>
}

export function generateComponentWCDts(component: ComponentRecord): string {
  return generateComponentWCDtsFile(component)
}

export function generateComponentWCDtsFile(
  component: ComponentRecord,
  options: GenerateComponentWCDtsOptions = {},
): string {
  const propTypeDeclarations = generatePropTypeDeclarations([component], {
    exported: options.exportPropTypes ?? true,
    reservedNames: mergeReservedNames(
      getGeneratedDeclarationNames([component]),
      options.reservedNames,
    ),
  })
  const resolvedComponent = propTypeDeclarations.components[0] ?? component
  const elementTypeName = getElementTypeName(resolvedComponent)
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  if (propTypeDeclarations.code) {
    lines.push(propTypeDeclarations.code)
    lines.push('')
  }
  lines.push(generateEventMap(resolvedComponent))
  lines.push('')
  lines.push(generateElementInterface(resolvedComponent))
  lines.push('')
  lines.push(`export declare const ${resolvedComponent.exportName}: {`)
  lines.push(`  new (): ${elementTypeName}`)
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

export function generateWCIndexDts(
  manifest: ComponentManifest,
  options: {
    getComponentImportPath: (component: ComponentRecord) => string
  },
): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')

  for (const component of manifest.components) {
    lines.push(
      `import type { ${getElementTypeName(component)} } from ${JSON.stringify(options.getComponentImportPath(component))}`,
    )
  }

  for (const component of manifest.components) {
    const importPath = JSON.stringify(options.getComponentImportPath(component))
    lines.push(`export { ${component.exportName} } from ${importPath}`)
    lines.push(
      `export type { ${getElementTypeName(component)}, ${getEventMapTypeName(component)} } from ${importPath}`,
    )
  }

  lines.push('')
  lines.push('declare global {')
  lines.push('  interface HTMLElementTagNameMap {')

  for (const component of manifest.components) {
    lines.push(
      `    ${JSON.stringify(component.tag)}: ${getElementTypeName(component)}`,
    )
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

function generateEventMap(component: ComponentRecord): string {
  const eventMapName = getEventMapTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${eventMapName} {`)

  for (const [key, event] of Object.entries(component.events)) {
    lines.push(
      `  ${safePropertyName(event.name ?? toKebabCase(event.key ?? key))}: ${formatEventType(event)}`,
    )
  }

  lines.push('}')
  return lines.join('\n')
}

function generateElementInterface(component: ComponentRecord): string {
  const eventMapName = getEventMapTypeName(component)

  return generateElementType(component, {
    eventMapTypeName: eventMapName,
  })
}

function toKebabCase(value: string): string {
  return value.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`)
}

function mergeReservedNames(
  defaults: ReadonlySet<string>,
  additional: ReadonlySet<string> | undefined,
): Set<string> {
  return new Set([...defaults, ...(additional ?? [])])
}
