import { formatPropType, isRequiredProp, safePropertyName } from './formatType'
import { getPropsTypeName } from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export function generateWCJsxDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateComponentJsxProps(component))
    lines.push('')
  }

  lines.push('declare global {')
  lines.push('  namespace JSX {')
  lines.push('    interface IntrinsicElements {')

  for (const component of manifest.components) {
    lines.push(
      `      ${JSON.stringify(component.tag)}: ${getPropsTypeName(component)}`,
    )
  }

  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

function generateComponentJsxProps(component: ComponentRecord): string {
  const propsTypeName = getPropsTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${propsTypeName} {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('')
  lines.push('  children?: unknown')
  lines.push('  class?: string')
  lines.push('  className?: string')
  lines.push(
    '  style?: string | Record<string, string | number | null | undefined>',
  )
  lines.push('  id?: string')
  lines.push('  role?: string')
  lines.push('  part?: string')
  lines.push('  slot?: string')
  lines.push('')
  lines.push('  [key: `data-${string}`]: unknown')
  lines.push('  [key: `aria-${string}`]: unknown')
  lines.push('}')

  return lines.join('\n')
}
