import {
  formatDetailType,
  formatMethodSignature,
  formatPropType,
  isRequiredProp,
  safePropertyName,
} from './formatType'
import { getElementTypeName, getPropsTypeName } from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export interface GenerateReactDtsOptions {
  namedSlots?: 'props' | 'none'
}

export function generateReactDts(
  manifest: ComponentManifest,
  options: GenerateReactDtsOptions = {},
): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  lines.push(`import type * as React from 'react'`)
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateReactComponentDts(component, options))
    lines.push('')
  }

  return lines.join('\n')
}

function generateReactComponentDts(
  component: ComponentRecord,
  options: GenerateReactDtsOptions,
): string {
  const propsTypeName = getPropsTypeName(component)
  const elementTypeName = getElementTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${propsTypeName} {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('')
  lines.push('  children?: React.ReactNode')
  lines.push('  className?: string')
  lines.push('  style?: React.CSSProperties')

  for (const [key, event] of Object.entries(component.events)) {
    const propName = event.reactName ?? toReactEventProp(event.key ?? key)
    const detailType = event.detail ? formatDetailType(event.detail) : 'unknown'
    lines.push(
      `  ${safePropertyName(propName)}?: (event: CustomEvent<${detailType}>) => void`,
    )
  }

  if (options.namedSlots !== 'none') {
    for (const name of Object.keys(component.slots)) {
      if (name === 'default') continue
      lines.push(`  ${safePropertyName(name)}?: React.ReactNode`)
    }
  }

  lines.push('}')
  lines.push('')
  lines.push(`export interface ${elementTypeName} extends HTMLElement {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  for (const method of Object.values(component.methods ?? {})) {
    lines.push(`  ${formatMethodSignature(method)}`)
  }

  lines.push('}')
  lines.push('')
  lines.push(
    `export declare const ${component.name}: React.ForwardRefExoticComponent<`,
  )
  lines.push(`  ${propsTypeName} & React.RefAttributes<${elementTypeName}>`)
  lines.push('>')

  return lines.join('\n')
}

function toReactEventProp(value: string): string {
  return `on${value
    .split('-')
    .filter(Boolean)
    .map(part => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('')}`
}
