// packages/web-c/component-dts/src/generateLoaderDts.ts

import { formatPropType, isRequiredProp, safePropertyName } from './formatType'
import { getElementTypeName } from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export function generateLoaderDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateElementInterface(component))
    lines.push('')
  }

  lines.push('export interface DefineCustomElementsOptions {')
  lines.push('  registry?: CustomElementRegistry')
  lines.push('}')
  lines.push('')
  lines.push(
    'export declare function defineCustomElements(options?: DefineCustomElementsOptions): void',
  )
  lines.push('')
  lines.push(
    'export declare const defineLazyElements: typeof defineCustomElements',
  )
  lines.push('')

  lines.push('declare global {')
  lines.push('  interface HTMLElementTagNameMap {')

  for (const component of manifest.components) {
    lines.push(
      `    ${JSON.stringify(component.tag)}: ${getElementTypeName(component)}`,
    )
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

function generateElementInterface(component: ComponentRecord): string {
  const elementTypeName = getElementTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${elementTypeName} extends HTMLElement {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'

    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('  componentOnReady(): Promise<this>')
  lines.push('}')

  return lines.join('\n')
}
