import {
  formatDetailType,
  formatPropType,
  isRequiredProp,
  safePropertyName,
} from './formatType'
import { getPropsTypeName } from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export function generateVueDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  lines.push(`import type { DefineComponent } from 'vue'`)
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateVueComponentDts(component))
    lines.push('')
  }

  return lines.join('\n')
}

export function generateVueGlobalDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  lines.push(`import type {`)

  for (const component of manifest.components) {
    lines.push(`  ${component.name},`)
  }

  lines.push(`} from './index'`)
  lines.push('')
  lines.push(`declare module 'vue' {`)
  lines.push('  export interface GlobalComponents {')

  for (const component of manifest.components) {
    lines.push(`    ${component.name}: typeof ${component.name}`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

function generateVueComponentDts(component: ComponentRecord): string {
  const propsTypeName = getPropsTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${propsTypeName} {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('}')
  lines.push('')
  lines.push(`export declare const ${component.name}: DefineComponent<`)
  lines.push(`  ${propsTypeName},`)
  lines.push('  {},')
  lines.push('  {},')
  lines.push('  {},')
  lines.push('  {},')
  lines.push('  {},')
  lines.push('  {},')
  lines.push(`  ${generateVueEmitsType(component)}`)
  lines.push('>')

  return lines.join('\n')
}

function generateVueEmitsType(component: ComponentRecord): string {
  const entries = Object.entries(component.events)
  const modelEntries = Array.from(
    new Map(
      (component.models ?? []).map(model => {
        const prop = component.props[model.prop]
        const type = prop ? formatPropType(prop) : 'unknown'
        const name = `update:${model.prop}`

        return [name, `${JSON.stringify(name)}: (value: ${type}) => void`]
      }),
    ).values(),
  )

  if (!entries.length && !modelEntries.length) {
    return '{}'
  }

  const fields = entries.map(([key, event]) => {
    const detailType = event.detail ? formatDetailType(event.detail) : 'unknown'
    return `${JSON.stringify(event.name ?? toKebabCase(event.key ?? key))}: (event: CustomEvent<${detailType}>) => void`
  })

  return `{ ${[...fields, ...modelEntries].join('; ')} }`
}

function toKebabCase(value: string): string {
  return value.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`)
}
