// packages/web-c/component-dts/src/generateLoaderDts.ts

import { generateElementType } from './generateElementType'
import { generatePropTypeDeclarations } from './generatePropTypeDeclarations'
import { getElementTypeName, getGeneratedDeclarationNames } from './naming'

import type { ComponentManifest } from '@zeus-js/component-analyzer'

export function generateLoaderDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  const propTypeDeclarations = generatePropTypeDeclarations(
    manifest.components,
    {
      reservedNames: getGeneratedDeclarationNames(manifest.components),
    },
  )
  if (propTypeDeclarations.code) {
    lines.push(propTypeDeclarations.code)
    lines.push('')
  }

  for (const component of propTypeDeclarations.components) {
    lines.push(
      generateElementType(component, {
        componentOnReady: true,
        forcePromise: true,
      }),
    )
    lines.push('')
  }

  lines.push('export declare function defineCustomElements(): void')
  lines.push('')
  lines.push(
    'export declare const defineLazyElements: typeof defineCustomElements',
  )
  lines.push('')

  lines.push('declare global {')
  lines.push('  interface HTMLElementTagNameMap {')

  for (const component of manifest.components) {
    lines.push(
      `    ${JSON.stringify(component.tag)}: ${getElementTypeName(component)}`,
    )
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}
