/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createPerson(name: string, age: number): Person

export declare function hello(name: string): string

export interface Person {
  name: string
  age: number
}

export declare function sum(a: number, b: number): number
