/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compiler(source: string, options: CompilerOptions): CompilerResult

export interface CompilerOptions {
  sourceType: string
  experimental: boolean
  target: string
  minify: boolean
}

export interface CompilerResult {
  code: string
  success: boolean
  errors: Array<string>
}
