// Symbol names used by the compiler
// These are the identifiers generated by the compiler

export const COMPILER_SYMBOLS = {
  // Template
  TEMPLATE_PREFIX: '_tmpl',
  TEMPLATE_VAR: '_tmpl',

  // Nodes
  NODE_PREFIX: '_el',
  TEXT_PREFIX: '_text',
  ANCHOR_PREFIX: '_anchor',
  REGION_PREFIX: '_region',

  // Bindings
  BIND_VAR: '_bind',
  EFFECT_VAR: '_effect',

  // Component
  COMPONENT_PREFIX: '_Comp',
  PROPS_VAR: 'props',
  HOST_VAR: '_host',

  // Slot
  SLOT_PREFIX: '_slot',

  // Root
  ROOT_VAR: '_root',
  DISPOSE_VAR: '_dispose',
} as const

export function templateName(index: number): string {
  return `${COMPILER_SYMBOLS.TEMPLATE_PREFIX}$${index}`
}

export function nodeVarName(index: number): string {
  return `${COMPILER_SYMBOLS.NODE_PREFIX}$${index}`
}

export function textVarName(index: number): string {
  return `${COMPILER_SYMBOLS.TEXT_PREFIX}$${index}`
}

export function anchorVarName(index: number): string {
  return `${COMPILER_SYMBOLS.ANCHOR_PREFIX}$${index}`
}

export function regionVarName(index: number): string {
  return `${COMPILER_SYMBOLS.REGION_PREFIX}$${index}`
}

export function slotVarName(index: number): string {
  return `${COMPILER_SYMBOLS.SLOT_PREFIX}$${index}`
}

export function componentName(index: number): string {
  return `${COMPILER_SYMBOLS.COMPONENT_PREFIX}$${index}`
}
