/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CompilerDiagnostic {
  code: string
  message: string
  severity: 'error' | 'warning'
  filename: string
  hint?: string
  span?: SourceSpan
}

export interface RawSourceMap {
  version: number
  file?: string
  sources: Array<string>
  sourceRoot?: string
  sourcesContent: Array<string | null>
  names: Array<string>
  mappings: string
}

export interface SourcePosition {
  offset: number
  line: number
  column: number
}

export interface SourceSpan {
  start: SourcePosition
  end: SourcePosition
}

export declare function transformModule(options: TransformModuleOptions): TransformModuleResult

export interface TransformModuleOptions {
  source: string
  filename: string
  target: 'dom' | 'ssr'
  runtimeModule: string
  delegateEvents: boolean
  sourceMap: boolean
}

export interface TransformModuleResult {
  code: string
  map: RawSourceMap | null
  diagnostics: Array<CompilerDiagnostic>
}
