export const CompilerErrorCode = {
  UNSUPPORTED_SPREAD_ATTRIBUTE: 'ZEUS_UNSUPPORTED_SPREAD_ATTRIBUTE',
  UNSUPPORTED_SPREAD_CHILD: 'ZEUS_UNSUPPORTED_SPREAD_CHILD',
  UNSUPPORTED_FRAGMENT: 'ZEUS_UNSUPPORTED_FRAGMENT',
  UNSUPPORTED_FRAGMENT_CHILD: 'ZEUS_UNSUPPORTED_FRAGMENT_CHILD',
  UNSUPPORTED_COMPONENT_PROP: 'ZEUS_UNSUPPORTED_COMPONENT_PROP',
  EMPTY_EXPRESSION: 'ZEUS_EMPTY_EXPRESSION',
  INVALID_TRANSFORM_RESULT: 'ZEUS_INVALID_TRANSFORM_RESULT',
  UNSUPPORTED_NODE: 'ZEUS_UNSUPPORTED_NODE',
  INVALID_BUILTIN_USAGE: 'ZEUS_INVALID_BUILTIN_USAGE',
  INVALID_REF_USAGE: 'ZEUS_INVALID_REF_USAGE',
} as const

export type CompilerErrorCode =
  (typeof CompilerErrorCode)[keyof typeof CompilerErrorCode]
