import {
  formatDetailType,
  formatPropType,
  isRequiredProp,
  safePropertyName,
} from './formatType'
import { getElementTypeName, getPropsTypeName } from './naming'

import type {
  ComponentManifest,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export function generateReactDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/component-dts.')
  lines.push('')
  lines.push(`import type * as React from 'react'`)
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateReactComponentDts(component))
    lines.push('')
  }

  return lines.join('\n')
}

function generateReactComponentDts(component: ComponentRecord): string {
  const propsTypeName = getPropsTypeName(component)
  const elementTypeName = getElementTypeName(component)
  const lines: string[] = []

  lines.push(`export interface ${propsTypeName} {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('')
  lines.push('  children?: React.ReactNode')
  lines.push('  className?: string')
  lines.push('  style?: React.CSSProperties')

  for (const [name, event] of Object.entries(component.events)) {
    const propName = toReactEventProp(name)
    const detailType = event.detail ? formatDetailType(event.detail) : 'unknown'
    lines.push(`  ${propName}?: (event: CustomEvent<${detailType}>) => void`)
  }

  lines.push('}')
  lines.push('')
  lines.push(`export interface ${elementTypeName} extends HTMLElement {`)

  for (const [name, prop] of Object.entries(component.props)) {
    const optional = isRequiredProp(prop) ? '' : '?'
    lines.push(
      `  ${safePropertyName(name)}${optional}: ${formatPropType(prop)}`,
    )
  }

  lines.push('}')
  lines.push('')
  lines.push(
    `export declare const ${component.name}: React.ForwardRefExoticComponent<`,
  )
  lines.push(`  ${propsTypeName} & React.RefAttributes<${elementTypeName}>`)
  lines.push('>')

  return lines.join('\n')
}

function toReactEventProp(eventName: string): string {
  return (
    'on' +
    eventName
      .split('-')
      .filter(Boolean)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('')
  )
}
