import type {
  ComponentManifest,
  ComponentProp,
  ComponentRecord,
} from '@zeus-js/component-analyzer'

export function generateWCDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/output-wc.')
  lines.push('')

  for (const component of manifest.components) {
    lines.push(generateElementInterface(component))
    lines.push('')
  }

  lines.push('declare global {')
  lines.push('  interface HTMLElementTagNameMap {')

  for (const component of manifest.components) {
    lines.push(`    ${JSON.stringify(component.tag)}: ${component.name}Element`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

export function generateWCJsxDts(manifest: ComponentManifest): string {
  const lines: string[] = []

  lines.push('/* eslint-disable */')
  lines.push('// Generated by @zeus-js/output-wc.')
  lines.push('')
  lines.push('declare global {')
  lines.push('  namespace JSX {')
  lines.push('    interface IntrinsicElements {')

  for (const component of manifest.components) {
    lines.push(
      `      ${JSON.stringify(component.tag)}: ${generateJsxPropsType(component)}`,
    )
  }

  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')
  lines.push('')

  return lines.join('\n')
}

function formatRequired(required?: boolean): string {
  return required ? '' : '?'
}

function generateElementInterface(component: ComponentRecord): string {
  const lines: string[] = []

  lines.push(`export interface ${component.name}Element extends HTMLElement {`)

  for (const [name, prop] of Object.entries(component.props)) {
    lines.push(
      `  ${name}${formatRequired(prop.required)}: ${formatPropType(prop)}`,
    )
  }

  lines.push('}')

  return lines.join('\n')
}

function generateJsxPropsType(component: ComponentRecord): string {
  const fields: string[] = []

  for (const [name, prop] of Object.entries(component.props)) {
    fields.push(
      `${name}${formatRequired(prop.required)}: ${formatPropType(prop)}`,
    )
  }

  fields.push('children?: unknown')
  fields.push('class?: string')
  fields.push('className?: string')
  fields.push('style?: string | Record<string, string | number>')

  return `{ ${fields.join('; ')} }`
}

function formatPropType(prop: ComponentProp): string {
  if (prop.values?.length) {
    return prop.values.map(value => JSON.stringify(value)).join(' | ')
  }

  switch (prop.type) {
    case 'string':
      return 'string'
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array':
      return 'unknown[]'
    case 'object':
      return 'Record<string, unknown>'
    default:
      return 'unknown'
  }
}
