// Compiler babel plugin entry point

export { default } from './plugin'
export * from './plugin'
export * from './component-analyzer'
export * from './jsx-to-ir'
export * from './ir-optimize'
export * from './ir-to-js'
export * from './transforms/dom-element'
export * from './transforms/component'
export * from './transforms/show'
export * from './transforms/for'
export * from './transforms/host'
export * from './transforms/slot'
export * from './dev-warnings'
