name: 'ci'
on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  pull_request:
    branches:
      - main
      - minor
  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    if: ${{ ! startsWith(github.event.head_commit.message, 'release:') && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) }}
    uses: ./.github/workflows/test.yml
    with:
      enable_hydration_browser_matrix: false
      hydration_browsers: chromium

  test-browser-matrix-nightly:
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/test.yml
    with:
      enable_hydration_browser_matrix: true
      hydration_browsers: chromium,firefox,webkit

  # continuous-release:
  #   if: github.repository == 'baicie/zeus'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v5

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4

  #     - name: Install Node.js
  #       uses: actions/setup-node@v5
  #       with:
  #         node-version-file: '.node-version'
  #         registry-url: 'https://registry.npmjs.org'
  #         cache: 'pnpm'

  #     - name: Install deps
  #       run: pnpm install

  #     - name: Build
  #       run: pnpm build-all

  # - name: Release
  #   run: pnpx pkg-pr-new publish --compact --pnpm './packages/*'
