name: Devtools Release

on:
  push:
    tags:
      - 'create-zeus@*'
      - 'vite-plugin@*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository == 'baicie/zeus'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish package
        run: pnpm standalone:publish "${{ github.ref_name }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
