name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: release
  cancel-in-progress: false

env:
  PUPPETEER_SKIP_DOWNLOAD: 'true'

jobs:
  release:
    if: github.repository == 'baicie/zeus'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Release precheck
        run: pnpm release:precheck

      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and publish
        run: pnpm release --publishOnly ${{ env.VERSION }} --skipBuild
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: yyx990803/release-tag@8cccf7c5aa332d71d222df46677f70f77a8d2dc0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/baicie/zeus/blob/main/CHANGELOG.md) for details.
